defaults:
- scope:
    path: ""
  values:
    layout: default

magick:
  lib_version: "6.9.13"
  version: "6.9.13-50"
  release_date: "2026-06-05"
  provenance_url: "https://github.com/ImageMagick/ImageMagick6/releases/download/6.9.13-50/ImageMagick-6.9.13-50.intoto.jsonl"
