defaults:
- scope:
    path: ""
  values:
    layout: default

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all

magick:
  lib_version: "6.9.13"
  version: "6.9.13-50"
  release_date: "2026-06-05"

